# Generated by Django 3.0.7 on 2020-07-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('status', models.DateTimeField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApi.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=66)),
                ('option1', models.CharField(blank=True, max_length=166)),
                ('option2', models.CharField(blank=True, max_length=166)),
                ('option3', models.CharField(blank=True, max_length=166)),
                ('option4', models.CharField(blank=True, max_length=166)),
                ('answer', models.CharField(max_length=166)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApi.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ans', models.CharField(blank=True, max_length=166)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApi.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApi.User')),
            ],
        ),
    ]
